# Generated by Django 3.1.1 on 2020-09-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='carcass',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='video_resolution',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='categoris',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='viewing_angle',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
