# Generated by Django 3.1.1 on 2020-09-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200915_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='categoris',
            new_name='name',
        ),
        migrations.AddField(
            model_name='categories',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.camera'),
        ),
    ]
