# Generated by Django 3.1.1 on 2020-09-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200915_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraimg',
            name='Camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='img', to='catalog.camera'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='Camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='catalog.camera'),
        ),
    ]
