# Generated by Django 3.1.1 on 2020-09-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200916_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='text',
        ),
    ]
