# Generated by Django 3.1.1 on 2020-09-16 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200917_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Camera',
            new_name='camera',
        ),
        migrations.AddField(
            model_name='comments',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
