# Generated by Django 3.1.1 on 2020-09-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200917_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='category',
        ),
        migrations.AddField(
            model_name='categories',
            name='camera',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='catalog.Camera'),
        ),
    ]
