# Generated by Django 3.1.1 on 2020-09-28 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_camerainstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraimg',
            name='Camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='catalog.camera'),
        ),
    ]
