# Generated by Django 3.1.1 on 2020-09-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200928_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
