# Generated by Django 3.1.1 on 2020-09-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='camera',
            field=models.ManyToManyField(related_name='category', to='catalog.Camera'),
        ),
    ]
